<?php
declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \FoundationCommerce\RumvisionTracking\ViewModel\TrackingScript $viewModel */
/** @var HyvaCsp $hyvaCsp */
$viewModel = $block->getData('view_model');
$siteId = $viewModel->getSiteId();
$domainName = $viewModel->getDomainName();

if (!$viewModel->isEnabled()) {
    return;
}
?>
<script>
    window.rumv = window.rumv || function() { (window.rumv.q = window.rumv.q || []).push(arguments) };
    (function(rum, vi,si,on) {
        var s = JSON.parse( sessionStorage.getItem('rumv') || '{"pageviews":0}' ); s.pageviews++;
        if ( s.urls && s.regex && ( s.page = eval('('+s.regex+')')( s.urls, vi.location.pathname ) ) && !s.page.type ) {
            return sessionStorage.setItem('rumv', JSON.stringify( s ) );
        }

        vi.rumv.storage = s;
        var head = si.querySelector('head'), js = si.createElement('script');
        js.src = 'https://d5yoctgpv4cpx.cloudfront.net/'+rum+'/v4-'+vi.location.hostname+'.js';
        head.appendChild(js);
    })( '<?= $escaper->escapeHtmlAttr($siteId) ?>', window, document, '<?= $escaper->escapeHtmlAttr($domainName) ?>' );
    //# sourceURL=rumvision.inline.js
</script>
<?php $hyvaCsp->registerInlineScript() ?>
